apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-nsme
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nscb-tenant/rhtap-demo-app/hacbs-test-project-nsme@sha256:295e819b5d933d92b6397100b097083f72692155cc9f435d6f050675449b4933
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
