apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-nsme
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-nsme
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-nsme
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-nsme
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-nsme
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nscb-tenant/rhtap-demo-app/hacbs-test-project-nsme@sha256:74c3b5b9dfaf111dd3890357ee9dda7f196672dfbd4c3f5e4cde6bcd37a596d0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
